package es.upm.etsisi.poo.domain.user;

import java.util.ArrayList;
import java.util.List;

import es.upm.etsisi.poo.domain.ticket.Ticket;

// Represents a cashier, as defined in E2.
public class Cashier extends User {
    private final List<Ticket> tickets;

    public Cashier(String id, String name, String email) {
        super(id, name, email);
        this.tickets = new ArrayList<>();
    }

    public static String generateCashierId(List<Cashier> existingCashiers) {
        String id;

        // E2 indication: IDs generated by: "UW" + 7 random digits
        do {
            
            int randomDigits = (int) (Math.random() * 10000000);
            // Format to ensure 7 digits with leading zeros if necessary
            id = "UW" + String.format("%07d", randomDigits);
        }
        // Before return check for taken ID
        while (isCashierIdTaken(id, existingCashiers));

        return id;
    }

    private static boolean isCashierIdTaken(String id, List<Cashier> existingCashiers) {
        for (Cashier cashier : existingCashiers) {
            if (cashier.getId().equals(id)) {
                return true;
            }
        }
        return false;
    }

    public void addTicket(Ticket ticket) {
        if (ticket == null) {
            throw new IllegalArgumentException("Ticket cannot be null.");
        }
        this.tickets.add(ticket);
    }

    public List<Ticket> getTickets() {
        return new ArrayList<>(tickets);
    }

    // Method to check if this cashier owns a specific ticket
    public boolean hasTicket(String ticketId) {
        for (Ticket ticket : tickets) {
            if (ticket.getId().equals(ticketId)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String toString() {
        // Returns a string representation of the Cashier, including id, name and email, in that order.
        return String.format("{class: Cashier, id: '%s', name: '%s', email: '%s'}",
                getId(), getName(), getEmail());
    }
}