package es.upm.etsisi.poo.common;

import java.util.List;

import es.upm.etsisi.poo.domain.product.Catalog;
import es.upm.etsisi.poo.domain.user.Cashier;

// A utility class with static methods for generating unique IDs.
public class IdGenerator {

    public static String generateCashierId(List<Cashier> existingCashiers) {
        String id;

        // E2 indication: IDs generated by: "UW" + 7 random digits
        do {
            
            int randomDigits = (int) (Math.random() * 10000000);
            // Format to ensure 7 digits with leading zeros if necessary
            id = "UW" + String.format("%07d", randomDigits);
        }
        // Before return check for taken ID
        while (isCashierIdTaken(id, existingCashiers));

        return id;
    }

    private static boolean isCashierIdTaken(String id, List<Cashier> existingCashiers) {
        for (Cashier cashier : existingCashiers) {
            if (cashier.getId().equals(id)) {
                return true;
            }
        }
        return false;
    }

    public static int generateProductId(Catalog catalog) {
        int id;
        boolean idTaken;
        
        do {
            // E2 indication: Generate a random ID for the product between 1 and 100000
            id = (int) (Math.random() * 100000) + 1;
            idTaken = false;
            // If getProduct doesn't throw ID is taken and idTaken remains false
            try {
                catalog.getProduct(id);
                idTaken = true;
            } catch (ProductNotFoundException e) {}
        } while (idTaken);
        return id;
    }
}